// <auto-generated />
using System;
using EFCoreOperatinsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreOperatinsApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreOperatinsApp.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfPages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("EFCoreOperatinsApp.Data.BookPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("BookPrices");
                });

            modelBuilder.Entity("EFCoreOperatinsApp.Data.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Indian Rupee",
                            Title = "INR"
                        },
                        new
                        {
                            Id = 2,
                            Description = "United States Dollar",
                            Title = "USD"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Euro",
                            Title = "EUR"
                        },
                        new
                        {
                            Id = 4,
                            Description = "British Pound Sterling",
                            Title = "GBP"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Japanese Yen",
                            Title = "JPY"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Australian Dollar",
                            Title = "AUD"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Canadian Dollar",
                            Title = "CAD"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Chinese Yuan",
                            Title = "CNY"
                        },
                        new
                        {
                            Id = 9,
                            Description = "United Arab Emirates Dirham",
                            Title = "AED"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Saudi Riyal",
                            Title = "SAR"
                        });
                });

            modelBuilder.Entity("EFCoreOperatinsApp.Data.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hindi Language",
                            Title = "Hindi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "English Language",
                            Title = "English"
                        },
                        new
                        {
                            Id = 3,
                            Description = "French Language",
                            Title = "French"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Spanish Language",
                            Title = "Spanish"
                        },
                        new
                        {
                            Id = 5,
                            Description = "German Language",
                            Title = "German"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chinese (Mandarin)",
                            Title = "Chinese"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Arabic Language",
                            Title = "Arabic"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Portuguese Language",
                            Title = "Portuguese"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Russian Language",
                            Title = "Russian"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Japanese Language",
                            Title = "Japanese"
                        });
                });

            modelBuilder.Entity("EFCoreOperatinsApp.Data.Book", b =>
                {
                    b.HasOne("EFCoreOperatinsApp.Data.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("EFCoreOperatinsApp.Data.BookPrice", b =>
                {
                    b.HasOne("EFCoreOperatinsApp.Data.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreOperatinsApp.Data.Currency", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("CurrencyType");
                });

            modelBuilder.Entity("EFCoreOperatinsApp.Data.Language", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
